# Generated by Django 3.2.8 on 2021-11-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=40)),
                ('en_html', models.TextField()),
                ('mn_html', models.TextField()),
                ('order_number', models.IntegerField()),
            ],
        ),
    ]
