# Generated by Django 3.0.2 on 2022-01-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_web_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
